configMapGenerator:
  - name: env-configs
    behavior: create
    literals:
      - APP_MODE=dev
      - MESSAGE=hello

generatorOptions:
  disableNameSuffixHash: false   # ‚ùå HASH ENABLED (CAUSES NEW REPLICASETS EVERY SYNC)
