resources:
  - ../../base

configMapGenerator:
  - name: env-configs
    behavior: create
    literals:
      - VERSION=random

generatorOptions:
  disableNameSuffixHash: false     # ❌ Hash enabled → ArgoCD triggers new RS on every sync
